import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const relativeGeneratedPath = "_includes/generated/api-reference.md";
const generatedPath = resolve(root, relativeGeneratedPath);
const manifest = readFileSync(resolve(root, "docs/api/API_REFERENCE.sha256"), "utf8").trim();
const match = manifest.match(/^([a-f0-9]{64})  (_includes\/generated\/api-reference[.]md)$/);
if (!match || match[2] !== relativeGeneratedPath) throw new Error("Invalid generated API reference manifest.");

const generated = readFileSync(generatedPath);
const actualHash = createHash("sha256").update(generated).digest("hex");
if (actualHash !== match[1]) throw new Error("Generated API reference drift detected; refresh it from platform-protos gen/docs/api.md.");

const text = generated.toString("utf8");
if (!text.startsWith("<!-- Code generated by cmd/proto-doc")) throw new Error("API reference is not marked as generated.");
for (const required of [
  "deepnavy.v1.BillingService",
  "ListInvoices",
  "deepnavy.v1.GitHubDeliveryService",
  "deepnavy.v1.AgentWorkAssignment",
  "RenewAgentWorkAssignment",
  "CompleteAgentWorkAssignment",
  "deepnavy.v1.SessionService",
  "deepnavy.v1.WorkspaceService"
]) {
  if (!text.includes(required)) throw new Error(`Generated API reference is missing ${required}.`);
}
/* The brand is lowercase everywhere it is written. This file, however, is not written
 * here - it is generated from platform-protos' proto comments and byte-compared against
 * that generation below, so the site cannot correct a spelling inside it. The fix for one
 * belongs upstream, in the .proto comment.
 *
 * platform-protos 31a489d8 introduced exactly one, in the AdminAuthorizationBasis enum
 * comment (proto/deepnavy/v1/admin.proto, "an active Deep Navy administrator identity").
 * It is quarantined here rather than ignored: the exact sentence is named, it must appear
 * exactly once, and every other occurrence still fails. A second one - or this one moving,
 * or a differently-worded one - trips the check again, which is what keeps this an
 * accounted-for upstream defect rather than a hole in the rule.
 *
 * TODO(platform-protos): lowercase the brand in that comment and delete this allowance. */
const KNOWN_UPSTREAM_BRAND_SPELLING = "an active Deep Navy<br> administrator identity";
const brandSpellings = (text.match(/Deep Navy/g) || []).length;
const quarantined = (text.split(KNOWN_UPSTREAM_BRAND_SPELLING).length - 1);
if (quarantined > 1) throw new Error(`The quarantined upstream brand spelling appears ${quarantined} times; it is allowed exactly once.`);
if (brandSpellings > quarantined) {
  throw new Error(
    `Generated API reference contains ${brandSpellings - quarantined} non-lowercase brand spelling(s) beyond the one known upstream comment. ` +
    "Fix the spelling in the platform-protos .proto comment it came from, then re-vendor."
  );
}

/* The published reference must be what platform-protos generated AT THE PINNED COMMIT.
 *
 * This used to compare against the sibling working tree, which is a live checkout other
 * people edit: an unrelated in-progress proto change turned gen/docs/api.md dirty and
 * failed this repository's build with a message blaming its own published reference.
 * Asking git for the commit answers the real question and keeps answering it while
 * platform-protos moves ahead. */
const siblingRoot = resolve(root, "../platform-protos");
const pinnedRevision = readFileSync(resolve(root, "vendor/platform-protos/REVISION"), "utf8").trim();
if (existsSync(resolve(siblingRoot, ".git")) && /^[0-9a-f]{40}$/.test(pinnedRevision)) {
  const known = spawnSync("git", ["-C", siblingRoot, "cat-file", "-e", `${pinnedRevision}^{commit}`]);
  if (known.status === 0) {
    const sibling = spawnSync("git", ["-C", siblingRoot, "show", `${pinnedRevision}:gen/docs/api.md`], { maxBuffer: 64 * 1024 * 1024 });
    if (sibling.status !== 0) throw new Error(`platform-protos ${pinnedRevision} has no gen/docs/api.md.`);
    if (!generated.equals(sibling.stdout)) {
      throw new Error(`Published API reference is not what platform-protos generated at ${pinnedRevision}. Refresh it from that commit's gen/docs/api.md.`);
    }
  }
}

const wrapper = readFileSync(resolve(root, "docs/api/index.md"), "utf8");
if (!wrapper.includes("{% include generated/api-reference.md %}")) throw new Error("API reference route does not include the generated body.");
for (const discoveryPath of ["docs/index.md", "_includes/footer.html", "llms.txt"]) {
  if (!readFileSync(resolve(root, discoveryPath), "utf8").includes("/docs/api/")) {
    throw new Error(`${discoveryPath} does not link to the generated API reference.`);
  }
}

console.log(`Verified generated API reference ${actualHash}.`);
