import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const relativeGeneratedPath = "_includes/generated/api-reference.md";
const generatedPath = resolve(root, relativeGeneratedPath);
const manifest = readFileSync(resolve(root, "docs/api/API_REFERENCE.sha256"), "utf8").trim();
const match = manifest.match(/^([a-f0-9]{64})  (_includes\/generated\/api-reference[.]md)$/);
if (!match || match[2] !== relativeGeneratedPath) throw new Error("Invalid generated API reference manifest.");

const generated = readFileSync(generatedPath);
const actualHash = createHash("sha256").update(generated).digest("hex");
if (actualHash !== match[1]) throw new Error("Generated API reference drift detected; refresh it from platform-protos gen/docs/api.md.");

const text = generated.toString("utf8");
if (!text.startsWith("<!-- Code generated by cmd/proto-doc")) throw new Error("API reference is not marked as generated.");
for (const required of [
  "deepnavy.v1.BillingService",
  "ListInvoices",
  "deepnavy.v1.GitHubDeliveryService",
  "deepnavy.v1.AgentWorkAssignment",
  "RenewAgentWorkAssignment",
  "CompleteAgentWorkAssignment",
  "deepnavy.v1.SessionService",
  "deepnavy.v1.WorkspaceService"
]) {
  if (!text.includes(required)) throw new Error(`Generated API reference is missing ${required}.`);
}
if (text.includes("Deep Navy")) throw new Error("Generated API reference contains a non-lowercase brand spelling.");

const siblingGenerated = resolve(root, "../platform-protos/gen/docs/api.md");
if (existsSync(siblingGenerated)) {
  const sibling = readFileSync(siblingGenerated);
  if (!generated.equals(sibling)) throw new Error("Published API reference differs from the current sibling platform-protos generation.");
}

const wrapper = readFileSync(resolve(root, "docs/api/index.md"), "utf8");
if (!wrapper.includes("{% include generated/api-reference.md %}")) throw new Error("API reference route does not include the generated body.");
for (const discoveryPath of ["docs/index.md", "_includes/footer.html", "llms.txt"]) {
  if (!readFileSync(resolve(root, discoveryPath), "utf8").includes("/docs/api/")) {
    throw new Error(`${discoveryPath} does not link to the generated API reference.`);
  }
}

console.log(`Verified generated API reference ${actualHash}.`);
