import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const expectedRevision = "c31599988b51dadbf06af6946b9e7cb211724e1e";
const expectedRuntimeVersions = Object.freeze({
  "@bufbuild/protobuf": "2.13.0",
  "@connectrpc/connect": "2.1.2",
  "@connectrpc/connect-web": "2.1.2"
});
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const vendorRoot = resolve(root, "vendor/platform-protos");
const revision = readFileSync(resolve(vendorRoot, "REVISION"), "utf8").trim();
if (revision !== expectedRevision) throw new Error(`Vendored platform-protos revision ${revision || "<empty>"} does not match ${expectedRevision}.`);

const manifestLines = readFileSync(resolve(vendorRoot, "MANIFEST.sha256"), "utf8").trim().split("\n");
const required = new Set([
  "activity",
  "admin",
  "agents",
  "approvals",
  "auth",
  "billing",
  "common",
  "conversations",
  "economics",
  "github",
  "github_delivery",
  "initiatives",
  "objectives",
  "organizations",
  "provisioning",
  "repositories",
  "sessions",
  "teams",
  "work",
  "workspaces"
].map((name) => `deepnavy/v1/${name}_pb.ts`));
for (const line of manifestLines) {
  const match = line.match(/^([a-f0-9]{64})  (deepnavy\/v1\/[a-z_]+_pb\.ts)$/);
  if (!match) throw new Error(`Invalid vendored descriptor manifest entry: ${line}`);
  const [, expectedHash, relativePath] = match;
  if (!required.delete(relativePath)) throw new Error(`Unexpected or duplicate vendored descriptor: ${relativePath}`);
  const contents = readFileSync(resolve(vendorRoot, relativePath));
  const hash = createHash("sha256").update(contents).digest("hex");
  if (hash !== expectedHash) throw new Error(`Vendored descriptor drift detected in ${relativePath}. Refresh it from platform-protos ${expectedRevision}.`);
  if (!contents.toString("utf8", 0, 100).includes("@generated by protoc-gen-es v2.12.1")) throw new Error(`${relativePath} is not the expected generated Protobuf-ES artifact.`);
}
if (required.size) throw new Error(`Missing vendored descriptors: ${[...required].join(", ")}`);

const packageText = readFileSync(resolve(root, "package.json"), "utf8");
if ((packageText.match(/"allowScripts"\s*:/g) || []).length !== 1) throw new Error("package.json must contain exactly one allowScripts policy.");
const packageJson = JSON.parse(packageText);
for (const [name, version] of Object.entries(expectedRuntimeVersions)) {
  if (packageJson.dependencies?.[name] !== version) throw new Error(`${name} must remain pinned to ${version} for platform-protos ${expectedRevision}.`);
}
if (packageJson.allowScripts?.["esbuild@0.28.1"] !== true || Object.keys(packageJson.allowScripts || {}).length !== 1) {
  throw new Error("Only esbuild@0.28.1 may run a dependency install script.");
}

const siblingRoot = resolve(root, "../platform-protos");
if (existsSync(resolve(siblingRoot, ".git"))) {
  const result = spawnSync("git", ["-C", siblingRoot, "rev-parse", "HEAD"], { encoding: "utf8" });
  if (result.status !== 0) throw new Error(`Could not inspect sibling platform-protos: ${result.stderr.trim()}`);
  if (result.stdout.trim() !== expectedRevision) throw new Error(`Sibling platform-protos is at ${result.stdout.trim()}, expected ${expectedRevision}.`);
  for (const relativePath of manifestLines.map((line) => line.split("  ")[1])) {
    const vendored = readFileSync(resolve(vendorRoot, relativePath));
    const generated = readFileSync(resolve(siblingRoot, "gen/ts", relativePath));
    if (!vendored.equals(generated)) throw new Error(`Vendored ${relativePath} differs from sibling platform-protos ${expectedRevision}.`);
  }
}

console.log(`Verified ${manifestLines.length} generated descriptors from platform-protos ${expectedRevision}.`);
